# Generated by Django 5.0.4 on 2024-05-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_emailsender_curse_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsender',
            name='name_sheet_curse',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
