# Generated by Django 5.0.4 on 2024-06-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_savefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='savefile',
            name='public_folder',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
