# Generated by Django 5.0.4 on 2024-06-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_savefile_public_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='savefile',
            name='path_for_smb_linux',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
