# Generated by Django 5.0.4 on 2024-06-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_savefile_path_for_smb_linux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savefile',
            name='file_name',
            field=models.CharField(max_length=200, verbose_name='Имя файла'),
        ),
        migrations.AlterField(
            model_name='savefile',
            name='file_path',
            field=models.CharField(max_length=200, verbose_name='Путь'),
        ),
        migrations.AlterField(
            model_name='savefile',
            name='host_name',
            field=models.CharField(max_length=50, verbose_name='Сервер'),
        ),
        migrations.AlterField(
            model_name='savefile',
            name='path_for_smb_linux',
            field=models.CharField(max_length=200, null=True, verbose_name='Путь для SMB Linux'),
        ),
        migrations.AlterField(
            model_name='savefile',
            name='public_folder',
            field=models.CharField(max_length=200, null=True, verbose_name='Публичная папка'),
        ),
        migrations.AlterField(
            model_name='savefile',
            name='user_name_samba',
            field=models.CharField(max_length=200, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='savefile',
            name='user_password_samba',
            field=models.CharField(max_length=200, verbose_name='Пароль'),
        ),
    ]
