# Generated by Django 5.0.4 on 2024-06-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_savefile_file_name_alter_savefile_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsender',
            name='curse_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='emailsender',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='emailsender',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='emailsender',
            name='name_sheet_curse',
            field=models.CharField(max_length=200, null=True, verbose_name='Страница курса в списке учеников'),
        ),
    ]
