# Generated by Django 5.0.4 on 2024-07-07 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_emailsender_curse_name_alter_emailsender_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_course', models.CharField(max_length=200, unique=True, verbose_name='Номер курса')),
                ('name_course', models.CharField(max_length=200, unique=True, verbose_name='Название курса')),
                ('sheet_curse', models.CharField(max_length=200, unique=True, verbose_name='Страница курса')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.courses', verbose_name='Номер курса')),
            ],
            options={
                'verbose_name': 'рассылку',
                'verbose_name_plural': 'Рассылка',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_teacher', models.CharField(max_length=200, verbose_name='Номер преподавателя')),
                ('first_name', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('second_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'преподавателя',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.DeleteModel(
            name='EmailSender',
        ),
        migrations.AddField(
            model_name='mailing',
            name='num_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher', verbose_name='Номер преподавателя'),
        ),
    ]
